# Generated by Django 4.2.17 on 2024-12-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spins_left',
            field=models.IntegerField(default=10),
        ),
    ]
