# Generated by Django 4.2.17 on 2024-12-30 08:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spin', '0002_alter_userprofile_spins_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hoạt động')),
                ('probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Xác suất')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Màu sắc')),
                ('category', models.CharField(choices=[('food', 'Food and Drink'), ('travel', 'Trip and Travel'), ('home', 'Home Activities'), ('sport', 'Exercise and Sport'), ('relax', 'Shopping and Relaxing'), ('learning', 'Learn and Skill'), ('culture', 'Culture and Art'), ('outdoor', 'Outdoor Activities')], max_length=50, verbose_name='Danh mục')),
            ],
        ),
        migrations.RemoveField(
            model_name='spinhistory',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spins_left',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spins_count',
            field=models.IntegerField(default=0, verbose_name='Số lượt quay đã thực hiện'),
        ),
        migrations.AlterField(
            model_name='spinhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm quay'),
        ),
        migrations.AlterField(
            model_name='spinhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
        migrations.AddField(
            model_name='spinhistory',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spin.activity', verbose_name='Kết quả quay'),
        ),
    ]
