# Generated by Django 4.2.17 on 2025-01-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0003_activity_remove_spinhistory_prize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField(verbose_name='Kết quả gợi ý từ API AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spin.userprofile', verbose_name='Người dùng')),
            ],
        ),
    ]
