# Generated by Django 4.2.17 on 2025-01-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0004_suggestionhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuggestionHistory',
            new_name='RecommendationsHistory',
        ),
    ]
