# Generated by Django 4.2.17 on 2025-01-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0006_rename_suggestion_recommendationshistory_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationshistory',
            name='topic',
            field=models.TextField(blank=True, null=True, verbose_name='Kết quả quay từ API spin_wheel'),
        ),
    ]
